### ISSUE TITLE
PDF vs HTML

### ISSUE THREAD

**Issue by yaytrio** [epicfaace/Tycho#3]
PDF:
- Easier for writers
- About the zooming, can't you zoom on a pdf?

HTML:
- What about it would look better?
- How difficult would it be or writers to use? It might be slightly off-putting

**Comment by epicfaace** [comment]
- Text will wrap nicely, you can zoom in or out of text easily. Like, for example, try zooming in and out of this page: http://epicfaace.github.io/tutorials/calculusIntro.html

  - On the other hand, zooming in on a PDF is ugly:  Wouldn't it be nicer if the text wrapped?
![image](https://cloud.githubusercontent.com/assets/1689183/25743604/2bae945a-3163-11e7-9956-839bda43f6b8.png)

- Here is how the wordpress editor looks.
![image](https://cloud.githubusercontent.com/assets/1689183/25743336/ca4227d2-3161-11e7-9f37-f6d473148ba7.png)

- Having said all that though, it does seem best for now to stick with PDF guides as it's easier to make and deal with on our side. (although not as user friendly I guess)
